<a href="https://colab.research.google.com/github/kahramankaya/Anlas-l-rEkonomiYoutube/blob/main/90.video(friedman%20testi).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#90.video(friedman testi)sıralamalı iki yönlü varyans analizi:tek yonlu tekrarlı anova nın non-parametrikte karsılıgı dır

In [18]:
import pandas as pd
import numpy as np
np.random.seed(5)
data=pd.DataFrame(
{
"kısıler":["A","B","C","D","X","Y"],
"testoncesı":np.random.randint(1000,size=(6)) ,  
"testsonrası1":np.random.randint(1000,size=(6)),
"testsonrası2":np.random.randint(1000,size=(6)),
"testsonrası3":np.random.randint(1000,size=(6)),
}
)
print(data)

  kısıler  testoncesı  testsonrası1  testsonrası2  testsonrası3
0       A         867            73           624           113
1       B         206             8           670           437
2       C         701           740           720           999
3       D         998           743           519            80
4       X         118           958           204            27
5       Y         400           411           911            44


In [19]:
# pingouin ile de normalliğe baktık yukarda stats ile de baktık.
veri=pd.melt(data,id_vars=["kısıler"],value_vars=["testoncesı","testsonrası1","testsonrası2","testsonrası3"])
veri.columns=["kısıler","testler","degerler"]
print(veri)

   kısıler       testler  degerler
0        A    testoncesı       867
1        B    testoncesı       206
2        C    testoncesı       701
3        D    testoncesı       998
4        X    testoncesı       118
5        Y    testoncesı       400
6        A  testsonrası1        73
7        B  testsonrası1         8
8        C  testsonrası1       740
9        D  testsonrası1       743
10       X  testsonrası1       958
11       Y  testsonrası1       411
12       A  testsonrası2       624
13       B  testsonrası2       670
14       C  testsonrası2       720
15       D  testsonrası2       519
16       X  testsonrası2       204
17       Y  testsonrası2       911
18       A  testsonrası3       113
19       B  testsonrası3       437
20       C  testsonrası3       999
21       D  testsonrası3        80
22       X  testsonrası3        27
23       Y  testsonrası3        44


In [20]:
from scipy import stats
normallık=stats.shapiro(veri["degerler"])
#normal dagılım degıl. ornek saysıda az old ıcın friedman a gecebiliriz.
print(normallık)

ShapiroResult(statistic=0.9063103795051575, pvalue=0.029355600476264954)


In [27]:
!pip install pingouin
import pingouin as pg
pgG=pg.normality(veri,group="testler",dv="degerler")
print(pgG)

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
                     W      pval  normal
testler                                 
testoncesı    0.928984  0.572276    True
testsonrası1  0.904348  0.400268    True
testsonrası2  0.948855  0.731000    True
testsonrası3  0.747376  0.018774   False


In [30]:
#friedman testi
fr=pg.friedman(data=veri,dv="degerler",within="testler",subject="kısıler")
#p-unc degerıne bak.h0 red edilmedi. yani test sonrasında yapılan testlerın test oncesınde bır farklılıgı yoktur.
print(fr)

           Source    W  ddof1    Q     p-unc
Friedman  testler  0.1      3  1.8  0.614935


In [35]:
#eger yukarda h0 red edilseydı bunu varsayarak yola cıkarsak posthoc uygulamalıyız. bu yapı array ile daha iyi çalıştıgından datayı arraya cevırmem gereklı.
!pip install scikit_posthocs
from scikit_posthocs import posthoc_conover_friedman
import numpy as np
arr=np.array([data["testoncesı"],data["testsonrası1"],data["testsonrası2"],data["testsonrası3"]])
print(arr)
print(posthoc_conover_friedman(arr,p_adjust="bonf"))
#cıkan sonucta  rakamlar 0,1,2,3 aslında testoncesı,testsonrası1... bunları ısfade eden bır matrıx yapısını verdı.
#ve degerler 0.05 ten buyuk oldugu ıcın gruplar arasında bır farklılık olmadıgını gosterdı. zaten frıedman testı farklılık olmadıgını soylemıstı.

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
[[867 206 701 998 118 400]
 [ 73   8 740 743 958 411]
 [624 670 720 519 204 911]
 [113 437 999  80  27  44]]
     0    1    2    3    4    5
0  1.0  1.0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0  1.0  1.0
3  1.0  1.0  1.0  1.0  1.0  1.0
4  1.0  1.0  1.0  1.0  1.0  1.0
5  1.0  1.0  1.0  1.0  1.0  1.0
