<a href="https://colab.research.google.com/github/kahramankaya/Anlas-l-rEkonomiYoutube/blob/main/devamet-73.video(One-Way%20ANOVA).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#73.video(One-Way ANOVA)

In [ ]:
import pandas as pd
from scipy import stats

data = [[120, 130, 110],
        [130, 120, 140],
        [140, 140, 130],
        [130, 130, 140],
        [120, 140, 120],
        [130, 120, 130],
        [140, 130, 140],
        [130, 140, 130],
        [120, 120, 110],
        [130, 130, 140]]

df_tedavi_yontemi_1 = pd.DataFrame(data[:,0], columns=["Tedavi Yöntemi 1"])
df_tedavi_yontemi_2 = pd.DataFrame(data[:,1], columns=["Tedavi Yöntemi 2"])
df_tedavi_yontemi_3 = pd.DataFrame(data[:,2], columns=["Tedavi Yöntemi 3"])

#1.adım: normallık testını yap. 2.adım varyans homojenlıgıne bak. 3. adım anova testını uygula. 1 ve 2 saglandıgında 3 e gecılır. ben dırek uzamasın dıye 3. adımı yazdım.
#yoksa shapiro ve barlett testlerini uygulalamalıyız.
fvalue, pvalue = stats.f_oneway(df_tedavi_yontemi_1,df_tedavi_yontemi_2,df_tedavi_yontemi_3)
print(fvalue, pvalue)


TypeError: ignored

In [ ]:
import numpy as np
# çift BOYUTLU SLICE(ALT KÜME) BULMA IŞLEMLERI  
a=np.random.randint(2,21,(4,5))
print(a)
print(a[:,2])# virgülden önceki tüm satırlar anlamına geliyor. virgülden sonra ki ise 2. sütun da kiler anlamına geliyor.


[[ 5  2  4 17 11]
 [ 6  9  5 17  7]
 [10  2  8  8 19]
 [10 15  9 14  6]]
[]
